#!/usr/bin/env python3
"""Check the policy-gated sqlc inputs and checked-in Go artifact snapshot."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "deploy" / "sqlc-artifacts.lock.json"
QUERY_NAME = re.compile(r"(?m)^-- name: ([A-Za-z][A-Za-z0-9_]*) :[a-z]+$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


def fail(message: str) -> None:
    raise ValueError(message)


def load_object(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"{path.relative_to(ROOT)} is not valid JSON: {error}") from error
    if not isinstance(value, dict):
        fail(f"{path.relative_to(ROOT)} must contain a JSON object")
    return value


def string_map(value: object, name: str) -> dict[str, str]:
    if not isinstance(value, dict) or not value:
        fail(f"{name} must be a non-empty object")

    result: dict[str, str] = {}
    for path, digest in value.items():
        if not isinstance(path, str) or not isinstance(digest, str):
            fail(f"{name} paths and digests must be strings")
        if not SHA256.fullmatch(digest):
            fail(f"{name} contains an invalid SHA-256 for {path}")
        result[path] = digest
    return result


def discovered_paths() -> tuple[set[str], set[str]]:
    inputs = {
        "server/sqlc.yaml",
        "server/pkg/db/schema.sql",
        *(
            path.relative_to(ROOT).as_posix()
            for path in (ROOT / "server" / "pkg" / "db" / "queries").rglob("*.sql")
        ),
    }
    outputs = {
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "server" / "pkg" / "db" / "gen").rglob("*.go")
    }
    if len(inputs) < 3:
        fail("sqlc inputs must include configuration, schema, and at least one query file")
    if not outputs:
        fail("checked-in sqlc Go output is missing")
    return inputs, outputs


def check_hashes(files: dict[str, str]) -> None:
    for relative_path, expected in sorted(files.items()):
        path = ROOT / relative_path
        if not path.is_file():
            fail(f"required sqlc artifact is missing: {relative_path}")
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != expected:
            fail(
                f"sqlc artifact drifted: {relative_path}; regeneration remains policy-gated, "
                "so review the server README and update the integrity lock deliberately"
            )


def check_query_surface(inputs: set[str], outputs: set[str], version: str) -> None:
    query_names: list[str] = []
    for relative_path in sorted(inputs):
        if "/queries/" not in relative_path:
            continue
        query_names.extend(QUERY_NAME.findall((ROOT / relative_path).read_text(encoding="utf-8")))

    if not query_names:
        fail("sqlc query files contain no named queries")
    if len(query_names) != len(set(query_names)):
        fail("sqlc query names must be unique")

    generated = "\n".join(
        (ROOT / relative_path).read_text(encoding="utf-8")
        for relative_path in sorted(outputs)
    )
    for relative_path in sorted(outputs):
        header = "\n".join(
            (ROOT / relative_path).read_text(encoding="utf-8").splitlines()[:6]
        )
        if not header.startswith("// Code generated by sqlc. DO NOT EDIT."):
            fail(f"checked-in output lacks the sqlc generated header: {relative_path}")
        if f"//   sqlc {version}" not in header:
            fail(f"checked-in output has the wrong sqlc version header: {relative_path}")

    missing_methods = [
        name
        for name in query_names
        if not re.search(rf"func \(q \*Queries\) {re.escape(name)}\(", generated)
    ]
    if missing_methods:
        fail(f"checked-in output is missing query methods: {', '.join(missing_methods)}")


def check_tracked(paths: set[str]) -> None:
    result = subprocess.run(
        ["git", "ls-files", "--", *sorted(paths)],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail("git could not inspect sqlc artifact tracking")
    tracked = set(result.stdout.splitlines())
    missing = sorted(paths.difference(tracked))
    if missing:
        fail(f"sqlc inputs/outputs must be tracked: {', '.join(missing)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--require-tracked",
        action="store_true",
        help="fail unless every locked input and output is tracked by Git",
    )
    args = parser.parse_args()

    try:
        manifest = load_object(MANIFEST_PATH)
        version = manifest.get("generatorVersion")
        if not isinstance(version, str) or not version:
            fail("sqlc artifact lock must declare generatorVersion")

        inputs = string_map(manifest.get("inputs"), "inputs")
        outputs = string_map(manifest.get("outputs"), "outputs")
        discovered_inputs, discovered_outputs = discovered_paths()
        if set(inputs) != discovered_inputs:
            fail("sqlc input inventory differs from deploy/sqlc-artifacts.lock.json")
        if set(outputs) != discovered_outputs:
            fail("sqlc output inventory differs from deploy/sqlc-artifacts.lock.json")

        check_hashes(inputs | outputs)
        check_query_surface(discovered_inputs, discovered_outputs, version)
        if args.require_tracked:
            check_tracked(
                discovered_inputs
                | discovered_outputs
                | {MANIFEST_PATH.relative_to(ROOT).as_posix()}
            )
    except (OSError, ValueError) as error:
        print(f"sqlc artifact check failed: {error}", file=sys.stderr)
        return 1

    print("sqlc inputs and checked-in artifacts match the policy-gated integrity lock.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
